- hosts: 15.0.0.43
  become: True
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: absent
    - name: copy local to remote machine
      copy:
        src: index.html
        dest: /var/www/html/
    - name: Start Apache server
      service:
        name: httpd
        enabled: yes
        state: started