- hosts: tomcat
  become: True
  tasks:
    - name: Delete user
      user:
        name: "{{ item.name }}"
        group: "{{ item.group }}"
        state: absent
      loop:
        - {name: 'anees', group: 'root'}
        - {name: 'tina', group: 'admins'}
    - name: Delete a group
      group:
        name: admins
        state: absent
