- hosts: tomcat
  become: True
  tasks:
    - name: Remove Apache
      yum:
        name: httpd
        state: absent
    - name: Remove App
      file:
        path: /var/www/html/
        state: absent