- hosts: tomcat
  become: True
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present
      tags:
        - Apache
    - name: Install git
        yum:
            name: git
            state: present
        tags:
            - Git