- hosts: tomcat
  become: True
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: absent
      tags:
        - Apache

    - name: Install git
      yum:
        name: git
        state: absent
      tags:
        - Git